// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function DeleteDatabase():Promise<void>;

export function GetAllMovies():Promise<Array<database.Movie>>;

export function GetMoviesByRating(arg1:number):Promise<Array<database.Movie>>;

export function GetMoviesByYear(arg1:number):Promise<Array<database.Movie>>;

export function GetStats():Promise<Record<string, any>>;

export function ScrapeUserData(arg1:string):Promise<void>;

export function SearchMovies(arg1:string):Promise<Array<database.Movie>>;
