// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDatabase() {
  return window['go']['main']['App']['DeleteDatabase']();
}

export function GetAllMovies() {
  return window['go']['main']['App']['GetAllMovies']();
}

export function GetMoviesByRating(arg1) {
  return window['go']['main']['App']['GetMoviesByRating'](arg1);
}

export function GetMoviesByYear(arg1) {
  return window['go']['main']['App']['GetMoviesByYear'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function ScrapeUserData(arg1) {
  return window['go']['main']['App']['ScrapeUserData'](arg1);
}

export function SearchMovies(arg1) {
  return window['go']['main']['App']['SearchMovies'](arg1);
}
